### ISSUE TITLE
Error in  3f198f0d4c79_g3wsuitedocker_postgis_1  Container

### ISSUE THREAD

**Issue by nikolaieniware** [g3w-suite/g3w-suite-docker#10]
Hello I just starting with your project, g3w-suite-docker  buid and install posgis, form branch v3.0.x OK , But when i start the containers with command  "docker-compose up"  ( to see the logs) without -d  . And  in console i saw this message from postgres. 

Operating System is Ubuntu 18.04.5 LTS (bionic)

The message is: 
 /docker-entrypoint.sh: line 52: kill: (12) - No such process
3f198f0d4c79_g3wsuitedocker_postgis_1 | Setup master database
3f198f0d4c79_g3wsuitedocker_postgis_1 | psql: could not connect to server: Connection refused
3f198f0d4c79_g3wsuitedocker_postgis_1 |         Is the server running locally and accepting
3f198f0d4c79_g3wsuitedocker_postgis_1 |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
3f198f0d4c79_g3wsuitedocker_postgis_1 | 2020-08-26 13:08:50.212 UTC [12] LOG:  listening on IPv4 address "127.0.0.1", port 5432
3f198f0d4c79_g3wsuitedocker_postgis_1 | 2020-08-26 13:08:50.305 UTC [12] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
3f198f0d4c79_g3wsuitedocker_postgis_1 | 2020-08-26 13:08:50.679 UTC [24] LOG:  database system was interrupted; last known up at 2020-08-26 13:07:46 UTC
3f198f0d4c79_g3wsuitedocker_postgis_1 | 2020-08-26 13:08:51.038 UTC [24] LOG:  database system was not properly shut down; automatic recovery in progress
3f198f0d4c79_g3wsuitedocker_postgis_1 | 2020-08-26 13:08:51.100 UTC [24] LOG:  redo starts at 0/30F7850
3f198f0d4c79_g3wsuitedocker_postgis_1 | 2020-08-26 13:08:51.100 UTC [24] LOG:  invalid record length at 0/30F8060: wanted 24, got 0
3f198f0d4c79_g3wsuitedocker_postgis_1 | 2020-08-26 13:08:51.100 UTC [24] LOG:  redo done at 0/30F7FF0
3f198f0d4c79_g3wsuitedocker_postgis_1 | 2020-08-26 13:08:51.100 UTC [24] LOG:  last completed transaction was at log time 2020-08-26 13:07:47.63654+00
3f198f0d4c79_g3wsuitedocker_postgis_1 | 2020-08-26 13:08:51.196 UTC [35] postgres@postgres FATAL:  the database system is starting up
3f198f0d4c79_g3wsuitedocker_postgis_1 | psql: FATAL:  the database system is starting up
3f198f0d4c79_g3wsuitedocker_postgis_1 | 2020-08-26 13:08:51.540 UTC [12] LOG:  database system is ready to accept connections
3f198f0d4c79_g3wsuitedocker_postgis_1 | 2020-08-26 13:08:51.547 UTC [42] LOG:  pg_cron scheduler started
3f198f0d4c79_g3wsuitedocker_postgis_1 |                                 List of databases
3f198f0d4c79_g3wsuitedocker_postgis_1 |       Name       |  Owner   | Encoding  | Collate | Ctype |   Access privileges
3f198f0d4c79_g3wsuitedocker_postgis_1 | -----------------+----------+-----------+---------+-------+-----------------------
3f198f0d4c79_g3wsuitedocker_postgis_1 |  data_production | g3wsuite | SQL_ASCII | C       | C     |
3f198f0d4c79_g3wsuitedocker_postgis_1 |  data_testing    | postgres | SQL_ASCII | C       | C     |
3f198f0d4c79_g3wsuitedocker_postgis_1 |  g3wsuite        | g3wsuite | SQL_ASCII | C       | C     |
3f198f0d4c79_g3wsuitedocker_postgis_1 |  postgres        | postgres | SQL_ASCII | C       | C     |
3f198f0d4c79_g3wsuitedocker_postgis_1 |  template0       | postgres | SQL_ASCII | C       | C     | =c/postgres          +
3f198f0d4c79_g3wsuitedocker_postgis_1 |                  |          |           |         |       | postgres=CTc/postgres
3f198f0d4c79_g3wsuitedocker_postgis_1 |  template1       | postgres | SQL_ASCII | C       | C     | =c/postgres          +
3f198f0d4c79_g3wsuitedocker_postgis_1 |                  |          |           |         |       | postgres=CTc/postgres
3f198f0d4c79_g3wsuitedocker_postgis_1 | (6 rows)
3f198f0d4c79_g3wsuitedocker_postgis_1 |
3f198f0d4c79_g3wsuitedocker_postgis_1 | postgres ready
3f198f0d4c79_g3wsuitedocker_postgis_1 | Setup postgres User:Password
3f198f0d4c79_g3wsuitedocker_postgis_1 | Creating superuser postgres
3f198f0d4c79_g3wsuitedocker_postgis_1 | ALTER ROLE
3f198f0d4c79_g3wsuitedocker_postgis_1 | Creating replication user replicator
3f198f0d4c79_g3wsuitedocker_postgis_1 | ALTER ROLE
3f198f0d4c79_g3wsuitedocker_postgis_1 |      datname     | datdba | encoding | datcollate | datctype | datistemplate | datallowconn | datconnlimit | datlastsysoid | datfrozenxid | datminmxid | dattablespace |               datacl

**Comment by wlorenzetti** [comment]
Hi @nikolaieniware I don't see nay error on log before, have you any problems ?

**Comment by nikolaieniware** [comment]
Hello thank you for your reply .  Only thing when i changed is the password for postigs , After installing the Portrainer for monitoring docker containers , i saw the postgis container is restarting every time when the trying to reach the postgis on this container. I don't know am i need to change more things in .env file configuration? Thanks.

**Comment by NyakudyaA** [comment]
@nikolaieniware The DB starting this way is by design. there is nothing wrong with those logs at all. Standard logs there.
