### ISSUE TITLE
Add MacroGroup - Server Error (500)

### ISSUE THREAD

**Issue by gustavoeugenio** [g3w-suite/g3w-suite-docker#101]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-suite-docker/issues) and this bug has never been reported before

### Subject of the issue

Error add macro group (Server Error (500)

### Steps to reproduce

1-Cartographic macro groups
2- Add Macro Group (+)

### Environment

- browser: google chrome
- operating system: __name and version (desktop or mobile)__
- g3w_suite docker compose 
- g3wsuite/g3w-suite:v3.6.x
- ubuntu server 22.04.2 LTS

**Comment by wlorenzetti** [comment]
Hi @gustavoeugenio, this issue it was closed with version v3.6.5 of G3W-ADMIN: https://github.com/g3w-suite/g3w-admin/pull/566. I just update the g3wsuite/g3w-suite:v3.6.x image on docker-hub, try to update your local image and run again g3w-suite.

**Comment by gustavoeugenio** [comment]
hi @wlorenzetti thank you so much. 

I updated today (with v3.6.x) and all right.
