### ISSUE TITLE
[Docker Desktop] Error decoding 'Volumes[0] invalid spec: :/shared-volume: empty section between colons

### ISSUE THREAD

**Issue by pravesh-kasare** [g3w-suite/g3w-suite-docker#102]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-suite-docker/issues) and this bug has never been reported before

### Subject of the issue

Hi,
recently i tried to configure G3W suite on my windows using docker desktop. G3W admin and client environment were created successfully, but while adding G3W docker suite got the below volume 0 invalid spec error.
i have followed each step suggested in documentation.
#help #docker_desktop

```
error decoding 'Volumes[0] invalid spec: :/shared-volume: empty section between colons
```

![Screenshot 2023-07-12 155055](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/ec21e4b7-4c39-4fdd-95ed-87adf6e36432)

### Steps to reproduce

![Screenshot 2023-07-12 155055](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/87f4f903-4e6d-404f-b9b3-06442f97e10f)

### Environment

- g3w-admin: 3.6
- g3w-client:3.8.5
- browser: edge
- operating system: Windows 11

**Comment by Raruto** [comment]
Hi @pravesh-kasare,

from the little I can see, it looks like you are trying to create a [dev environment](https://docs.docker.com/desktop/dev-environments/) through the Docker Desktop GUI's.

We have no previous experience with them, but that error may be due to the fact that the `.env` file (ref: missing `WEBGIS_DOCKER_SHARED_VOLUME` variable) is not being automatically loaded in here:

https://github.com/g3w-suite/g3w-suite-docker/blob/0fa27949155c222d96e59bc67ad25358c9cd9c9d/docker-compose-dev.yml#L67-L69

Please note that the steps to create the development docker container are currently located in here:

https://github.com/g3w-suite/g3w-suite-docker/blob/0fa27949155c222d96e59bc67ad25358c9cd9c9d/README_DEV.md?plain=1#L1-L10

Anyway, I suggest you to directly follow [g3w-client](https://github.com/g3w-suite/g3w-client/blob/dev/README.md)'s dev instructions (which right now are a litte bit more detailed / updated) if you intend to develop something for g3w-suite using a docker container.

👋 Raruto

**Comment by pravesh-kasare** [comment]
i have had added shared volume in .env file and follwed the steps as mentioned in g3w docker suite but the same error displaying

![Screenshot 2023-07-14 114015](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/2c5e222a-69dd-4d90-b1ab-1ff60788365d)

**Comment by Raruto** [comment]
@pravesh-kasare Docker Desktop [**Dev Environments**](https://docs.docker.com/desktop/dev-environments/) **(beta)** are an undocumented / unsupported method to install g3w-suite..

> i have had added shared volume in .env file

Then to create development container (first time only) you need to run the following command within a **Windows Terminal** (powershell or command prompt):

```sh
cd path/to/your/workspace/g3w-suite-docker/

docker compose -f docker-compose-dev.yml up -d
```

And after that, once it's done, in Docker Desktop you should see something like the following within the **Containers** tab:

![image](https://github.com/g3w-suite/g3w-suite-docker/assets/9614886/30a5bc0e-3a0c-4179-908f-aae217bdd80e)

https://github.com/g3w-suite/g3w-suite-docker/blob/0fa27949155c222d96e59bc67ad25358c9cd9c9d/README_DEV.md?plain=1#L1-L10

👋 Raruto

**Comment by pravesh-kasare** [comment]
loading project: volumes must be a mapping 
don't know where things went wrong...
![Screenshot 2023-07-14 165223](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/f64b3ecc-4f35-4c37-a4d5-004e068fbc3c)

**Comment by pravesh-kasare** [comment]
![image](https://github.com/g3w-suite/g3w-suite-docker/assets/104752346/058a8a3f-8ef4-400f-aa5f-4cad7ec880c3)

**Comment by pravesh-kasare** [comment]
can you please check it on my laptop remotely.

**Comment by Raruto** [comment]
> loading project: volumes must be a mapping
> don't know where things went wrong...

I'll be pedantic, as per g3w-suite@v3.6 the **necessary steps to follow to start working via docker are detailed [here](https://github.com/g3w-suite/g3w-client/blob/dev/README.md) and [here](https://github.com/g3w-suite/g3w-suite-docker/blob/dev/README_DEV.md)** (ie. projects structure, configuration files and other commands to be used from the terminal), **other installation methods are not currently supported.**

From what little you show, **it seems that you are trying to use a your own customized version** of the `docker-compose-dev.yml` file (and not the default one provided in [here](https://github.com/g3w-suite/g3w-suite-docker/blob/0fa27949155c222d96e59bc67ad25358c9cd9c9d/docker-compose-dev.yml)).

If not, please create a [new issue](https://github.com/g3w-suite/g3w-suite-docker/issues/new/choose) and provide as much detail as possible in your first comment to allow anyone else trying to understand what you are trying to do (**NB: reporting to others your steps-by-step is crucial to understanding what is going wrong**).

> can you please check it on my laptop remotely.

In this regard, sales department is available at info@gis3w.it for dedicated assistance or installations.

👋 Raruto
