### ISSUE TITLE
ArcGIS Rest Servers bug / feature ?

### ISSUE THREAD

**Issue by FITCODE1** [g3w-suite/g3w-suite-docker#104]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-suite-docker/issues) to make sure this feature hasn't been requested already.

### Motivation

Hello,

We need to use an ArcGIS Rest Servers connection in g3w through the QGIS project.

In the QGIS project I created an ArcGIS Rest Servers connection using https://geoportal.ancpi.ro/maps/rest/services.
I loaded the project in g3w and it doesn't work. TimeOut.
I removed the ArcGIS connection from the QGIS project. I reloaded. G3W works.

I tried directly in g3w through WMS. But.. Error.

Honestly, I don't know if we are talking about a bug or if it requires development.

### Suggested solution

Is it dev?

### Alternatives considered

<img width="647" alt="Screenshot 2023-07-19 at 14 10 31" src="https://github.com/g3w-suite/g3w-suite-docker/assets/35298984/3ad4c67f-99e8-4875-9909-d80365253255">

**Comment by Raruto** [comment]
Hi @FITCODE1,

it's most likely a bug, please open a new **bug report** (in [here](https://github.com/g3w-suite/g3w-admin/issues/new?assignees=wlorenzetti&labels=bug&projects=&template=bug_report.yml) or [here](https://github.com/g3w-suite/g3w-client/issues/new?assignees=volterra79&labels=bug&projects=&template=bug_report.yml) based on where you first experience this issue: ie. admin dashboard or frontend map) specifying all the necessary information:

- **Environment**: ie. software versions you have already tested against
- **Link to your project**: a link to a public project you are having problems with \*
- **Additional info**: any other information useful for others to understand and replicate your current situation (e.g. error logs, additional server configurations, self-explanatory images, ...)


\* attaching a problematic qgis project it's also fine.. 👉 [Minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)

👋 Raruto
