### ISSUE TITLE
dependencies image build error

### ISSUE THREAD

**Issue by nislamnreca** [g3w-suite/g3w-suite-docker#11]
When I issue the command:
docker build -f Dockerfile.g3wsuite-deps.ltr.dockerfile -t g3wsuite/g3w-suite-deps:latest --no-cache .
it starts and after some time I get the error like:
.....
Get:374 http://archive.ubuntu.com/ubuntu bionic/universe amd64 wait-for-it all 0.0~git20170723-1 [4340 B]
Fetched 131 MB in 7min 15s (302 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.6/libpython3.6-dev_3.6.9-1~18.04ubuntu1.1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update && apt install -y     libxml2-dev     libxslt-dev     postgresql-server-dev-all     libgdal-dev     python3-dev     libgdal20     python3-gdal     python3-pip     curl     wget     vim     wait-for-it     gdal-bin     libsqlite3-mod-spatialite     dirmngr     xvfb' returned a non-zero code: 100

**Comment by wlorenzetti** [comment]
I just tried it and it works  form me. How old is it your _ubuntu:bionic_ docker image?

Try to update it `docker pull ubuntu:bionic`
