### ISSUE TITLE
Setting Layer Opacity and Layer Reordiring

### ISSUE THREAD

**Issue by nislamnreca** [g3w-suite/g3w-suite-docker#12]
I expected option to change layer opacity and layer reordering by right button click on the layer name in layer the tree, and did not find it.
Is there a way to set layer opacity and re-order layer in the map?

**Comment by wlorenzetti** [comment]
Tha main rule into G3W-SUITE is QGIS-desktop and its projects are the masters :). So if you want to reorder or change layers opacity, you have to do it on your QGIS desktop save the project and upload again it on G3W-SUITE.
