### ISSUE TITLE
Client failed to fetch map (connection error)

### ISSUE THREAD

**Issue by serverul** [g3w-suite/g3w-suite-docker#128]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-suite-docker/issues) and this bug has never been reported before

### Subject of the issue

After a fresh install and uploading the project files together with the qgis project, everything seems to by ok. But when I try to acces the map I receive the error show in image.

![image](https://github.com/user-attachments/assets/a2483659-9871-4839-80a3-8cf0888ac347)

Oops!
TypeError: Failed to fetch
At the moment is not possible show map
Connection error

Where is this coming from ? 

### Steps to reproduce

1. Fresh g3w-suite docker install
2. Upload project files
3. Upload qgis project
4. View map

### Environment

- g3w-admin: Version 3.8.dev-20241127142837
- browser: vivaldi, brave
- operating system: windows

**Comment by serverul** [comment]
It was a web server port issue as I changed it in `docker-compose.yml`.

**Comment by danielm-t** [comment]
Hello I am running into a similar issue, how did you fix it? @serverul

**Comment by wlorenzetti** [comment]
@danielm-t I just push a fix for it: https://github.com/g3w-suite/g3w-suite-docker/commit/cc62356f5f63438c52e31c3ed30befd4c44111c2

Try to add $server_port in `config/nginx/django` like in commit above.

**Comment by gvina** [comment]
@danielm-t change docker-compose.yml in the nginx section:

```yml
  nginx:
    image: nginx
    ports:
      - "80:8080"
      - "443:443"
```

Expose Nginx on 80 (host) instead of 8080.
