### ISSUE TITLE
file style.css missing

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-suite-docker#16]
The README.md states:
```
A custom CSS is added to the pages, the file is located in config/g3w-suite/overrides/static/style.css and can be modified directly, changes are effective immediately.
```
unfortunately the **style.css** file is missing from repo.

**Comment by lucamanga** [comment]
bump. Anyone listening here?

**Comment by wlorenzetti** [comment]
Hi @lucamanga, sorry but in this period we are very busy for some projects we are working on!. I don't follow this part of dockerization, I hope it is not a refuse. Take patience.
