### ISSUE TITLE
Instructions on how to update from 3.0 to 3.1

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-suite-docker#19]
Hello,

can you write in the documentation on how to update the docker from 3.0 to 3.1?
The 3.0 database will be automatically updated?

Thank you in advance
Luca

**Comment by wlorenzetti** [comment]
Hi @lucamanga thanks for suggestion.
Yes just need to change docker image tag from v3.0.x to v3.1.x into docker-compose.yml file or just update your g3w-admin code and re-build your image. Thanks to Django features database will be updated.

**Comment by lucamanga** [comment]
Sorry for late response. Ok, it's now working, thank you :-)
