### ISSUE TITLE
Enable multiple backends which are OGC compliant

### ISSUE THREAD

**Issue by NyakudyaA** [g3w-suite/g3w-suite-docker#2]
# Problem

Since QGIS is ogc compliant and this is meant to create maps which are rich in cartography or bridging the gap between QGIS Server and publishing maps it would be nice to be able to add other sources from OWS services

ie GeoServer,Mapserver

**Comment by wlorenzetti** [comment]
G3W-SUITE born with this goal, at the starting project we think about it as a multiple backend OGC system, but for our business plans we choose to stay only QGIS-server.
