### ISSUE TITLE
g3w-suite/postgis error(?)

### ISSUE THREAD

**Issue by NikosTsompanides** [g3w-suite/g3w-suite-docker#22]
Hello! I tried to build and run g3w-suite with docker but g3w-suite/postgis seems to struggle to build.
From the logs i can see that postgres is constantly trying to re-connect but the following log appears: `/docker-entrypoint.sh: line 52: kill: (12) - No such process`
![Screenshot from 2021-01-05 11-18-21](https://user-images.githubusercontent.com/26706846/103629255-c23dc600-4f48-11eb-8e53-1ed5e2afd8f6.png)

The steps i follow are: 

1. `docker build -f Dockerfile.g3wsuite.dockerfile -t g3wsuite/g3w-suite:dev --no-cache .`
2. `docker build -f Dockerfile.g3wsuite-deps.ltr.dockerfile -t g3wsuite/g3w-suite-deps-ltr:dev --no-cache .`
3.  `docker build -f Dockerfile.postgis.dockerfile -t g3wsuite/postgis:11.0-2.5 .`
4. `docker-compose up -d`

Server details:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:         16.04
Codename:     xenial

I also try to build the stack with the mdillon/postgis:latest image and it works perfectly :/
Am i missing something in the building proccess  or this is a problem whith the g3w-suite/postgis image?
Thanks in advance!

**Comment by wlorenzetti** [comment]
Hi @NikosTsompanides from above screenshot I see that you are using 'dev' branch, I suggest you to use 'v3.1.x' branch realease. 'dev' branch is under development and can be broke.

**Comment by NikosTsompanides** [comment]
Hi @wlorenzetti and thanks for your immediate response!
Same error appears when i use v3.1.x banch :/ 
Steps i folllow:

1. git clone https://github.com/g3w-suite/g3w-suite-docker.git **_--branch v3.1.x_**
2. cd to folder
3. docker  build -f Dockerfile.g3wsuite.dockerfile -t g3wsuite/g3w-suite:**_v3.1.x_** --no-cache .
4. docker build -f Dockerfile.g3wsuite-deps.ltr.dockerfile -t g3wsuite/g3w-suite-deps-ltr:**_v3.1.x_** --no-cache .
5. docker build -f Dockerfile.postgis.dockerfile -t g3wsuite/postgis:11.0-2.5 .
6. docker-compose up -d

**Comment by wlorenzetti** [comment]
Please can you upload your log?

**Comment by NikosTsompanides** [comment]
Good morning! Here are the logs.
![Screenshot from 2021-01-07 09-54-17](https://user-images.githubusercontent.com/26706846/103866391-5f763700-50ce-11eb-8e01-679f068dd059.png)
![Screenshot from 2021-01-07 09-54-35](https://user-images.githubusercontent.com/26706846/103866394-60a76400-50ce-11eb-9753-8d042cd40541.png)

As you can see after the `/docker-entrypoint.sh: line 52: kill: (13) - No such proces` log postgis tryng to reconnect without success

**Comment by wlorenzetti** [comment]
Hi @NikosTsompanides, it's very strange...
I suggest you to user docker hub postgis image [g3wsuite/postgis](https://hub.docker.com/r/g3wsuite/postgis): delete your current g3wsuite/postgis image and restart your docker-compose, It'll pull image from docker hub.

**Comment by wlorenzetti** [comment]
Hi @NikosTsompanides it works now? I can close the isseu?
