### ISSUE TITLE
Standalone QGIS Server container

### ISSUE THREAD

**Issue by NyakudyaA** [g3w-suite/g3w-suite-docker#25]
It seems the `g3wsuite/g3w-suite:dev` image installs the native QGIS Server within the image. This is against the principle of docker where containers should be self-contained. 

What was the motivation for this because we can no longer scale the QGIS Server in production environments? Is there a way to use a standalone QGIS Server container with the stack

**Comment by wlorenzetti** [comment]
Hi @NyakudyaA , this because from version 3.x.x a full python qgis/qgis-server API integration is done thanks to great work of @elpaso. So G3W-SUITE doesn't wrap QGIS-server as it did until version 3.x.x but it works itself as QGIS-server :).

**Comment by NyakudyaA** [comment]
So if I want to scale QGIS Server I just scale the g3wsuite container?

**Comment by wlorenzetti** [comment]
Yes

**Comment by elpaso** [comment]
@NyakudyaA you can also raise the number of gunicorn instances of the suite inside a container but that would mean restarting the container itself which you probably don't want to happen.

**Comment by NyakudyaA** [comment]
Thanks @elpaso @wlorenzetti
