### ISSUE TITLE
Qgs Upload Error

### ISSUE THREAD

**Issue by fload** [g3w-suite/g3w-suite-docker#26]
I keep Getting this error when trying to upload a project, I am using qgis 3.16.3 and am not sure what I am missing.

[Project error on layers()]-- [Layer error on layerType(_6583ab07_d566_4c92_b52a_0e2626c93958)]-- 'NoneType' object has no attribute 'name'

(All layers are "postgis" layers on the cloud)

**Comment by wlorenzetti** [comment]
Hi @fload what version or branch of G3W-SUITE are you using? if you are using v3.1.x I suggesto you to use QGIS 3.10.14 last LTS version. A question your project have authcfg kye into datasource or did you save your user and password PostgreSQL into the project file?
At the momente only dev branch support authcfg for db connection, but dev is not stable and it'll become v3.2.x very soon

**Comment by fload** [comment]
g3wsuite/g3w-suite:dev,  Just working on getting some of our data into g3w, I will try the LTS qgis. I am not sure what an authcfg key is, I just added our postgis server as a data source. I did however try to save the included qgis "world" layer and load it as both qgs and qgz and got same error.

**Comment by fload** [comment]
Name
DroneImages
Source
dbname='postgres' host=34.67.160.46 port=5432 sslmode=allow authcfg=0kypw54 key='id_0' srid=4326 type=Point checkPrimaryKeyUnicity='1' table="public"."DroneImages" (geom) sql=
Storage
PostgreSQL database with PostGIS extension
Comment

Encoding

Geometry
Point (Point)
CRS
EPSG:4326 - WGS 84 - Geographic
Extent
-79.6231128333332947,36.9339873055555969 : -79.5690539444444056,36.9582637777778018
Unit
degrees
Feature count
229

**Comment by wlorenzetti** [comment]
into your datasource: `dbname='postgres' host=34.67.160.46 port=5432 sslmode=allow authcfg=0kypw54 key='id_0' srid=4326 type=Point checkPrimaryKeyUnicity='1' table="public"."DroneImages" (geom) sql=`
missing `user` and `password`. 
Try to save they in clears mode into the project.

@elpaso with branch `dev` authcfg it'll works?

**Comment by fload** [comment]
Thank you so much for your support one more question, Where would one add the user and password fields? (I had simply dragged a single db layer onto a new project and saved).

**Comment by fload** [comment]
I believe I have found it after right clicking the db and changing the credentials there now it shows username and pass, however same error..

[Project error on layers()]-- [Layer error on layerType(_8548770a_215b_4a8d_96d0_1ec2b55e492e)]-- 'NoneType' object has no attribute 'name'

I am also seeing these in docker logs
Layer _8548770a_215b_4a8d_96d0_1ec2b55e492e is not found into layerTreeRoot
postgis_1    | 2021-02-16 18:11:25.998 UTC [329] root@root FATAL:  role "root" does not exist

**Comment by fload** [comment]
Got it working I believe it was because the maps were made in qgis 3.16 instead of 3.10? (and also authentication)
