### ISSUE TITLE
Docker Question

### ISSUE THREAD

**Issue by fload** [g3w-suite/g3w-suite-docker#27]
Sorry if this is the wrong place to ask but I'm new to learning docker and just wondering how or if its possible to use a cloud storage bucket as the persistent data storage. It looks to me like I would just need to set it up as an env variable but I am not exactly sure I understand docker well enough yet.... Any direction would be most appreciated.

**Comment by fload** [comment]
after some considerations I believe the intended workflow is to edit the /config/settings_docker.py,
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('G3WSUITE_POSTGRES_DBNAME'),
        'USER': os.getenv('G3WSUITE_POSTGRES_USER_LOCAL') if os.getenv('G3WSUITE_POSTGRES_USER_LOCAL') else "%s@%s" % (
        os.getenv('G3WSUITE_POSTGRES_USER'), os.getenv('G3WSUITE_POSTGRES_HOST')),
        'PASSWORD': os.getenv('G3WSUITE_POSTGRES_PASS'),
        'HOST': os.getenv('G3WSUITE_POSTGRES_HOST'),
        'PORT': os.getenv('G3WSUITE_POSTGRES_PORT'),
    }
}

Am I on the right path?

**Comment by wlorenzetti** [comment]
Hi @fload sorry but I can help you on this. Is possible to use a cloud bucket storage for persistent data into docker, but I think it's not possible with only a simple env variable.
Searching on Docker docs, I found that you can use docker plugins to use a cloud storage as volume:
https://docs.docker.com/engine/extend/legacy_plugins/

I hope this can help you.
