### ISSUE TITLE
Syntax error: /scripts/setup.sh:

### ISSUE THREAD

**Issue by diegovarelajp** [g3w-suite/g3w-suite-docker#30]
When I trying to install through the docker gis3w by executing the command "docker build -f Dockerfile.g3wsuite.dockerfile -t g3wsuite/g3w-suite:dev --no-cache ." I am receiving the following error message as shown in the images
![issue1](https://user-images.githubusercontent.com/52501453/119839801-d0ca5100-beda-11eb-84e7-a592ca6eb443.png)

![issue2](https://user-images.githubusercontent.com/52501453/119839569-a5dffd00-beda-11eb-8ff8-f6492d271838.png)

**Comment by diegovarelajp** [comment]
Is it because my operating system is windows?

**Comment by wlorenzetti** [comment]
In effect I just try the build statement but on my Ubuntu 18.04 it works well! 
Yes this is only for linux systems, I didn't try it on windows, but it's strange because it running inside a docker linux image!
I suggest you to try it ona VM linux if you can.

**Comment by diegovarelajp** [comment]
Ok, I will try on vm linux. Thanks @wlorenzetti

**Comment by spaciandd** [comment]
@diegovarelajp @wlorenzetti 
Just go to **scripts** folder and open each file in VS Code and at right bottom change **CLRF to LF**.
![Screenshot_1](https://user-images.githubusercontent.com/33995618/150649131-e8f28433-73a8-4bdf-a02e-1dfe3dd7976c.png)
