### ISSUE TITLE
Openssh-error

### ISSUE THREAD

**Issue by ghost** [g3w-suite/g3w-suite-docker#34]
![err_6](https://user-images.githubusercontent.com/88318354/130047155-b7c1d2f7-0762-4d00-a61a-44a4472d2582.PNG)
Sto installando la versione dockerizzata, ma quando eseguo il comando "docker build --build-arg G3W_SUITE_BRANCH=v.3.2.x -f Dockerfile.g3wsuite.dockerfile -t g3wsuite/g3w-suite:v3.2.x --no-cache .", ho il seguente errore.
Come posso risolverlo?

**Comment by wlorenzetti** [comment]
Salve Francesco, 
sembra un problema legato all'immagine base di Ubuntu, cerco di verificare al più presto.

**Comment by ghost** [comment]
Grazie

**Comment by ghost** [comment]
Qualche novità?

**Comment by wlorenzetti** [comment]
@Francesco2102 un problema legato all'immagine docker base non aggiornata sul repository docker.
Per Installare G3W-SUITE docker può fare in due maniere o creare le due immagini principali g3wsuite/g3w-suite-deps:v3.2.x e g3wsuite/g3w-suite:v3.2.x oppure solo la seconda mentre la prima la scarichi dal repository presente su docker-hub.

Ti consiglio di cancellare tutte le immagini docker presente sulla tua macchina virtuale e ripartire sa capo.
Crea solo l'immagine g3wsuite/g3w-suite:v3.2.x 
```
docker build --build-arg G3W_SUITE_BRANCH=v.3.2.x -f Dockerfile.g3wsuite.dockerfile -t g3wsuite/g3w-suite:v3.2.x --no-cache .
```

pooi configura il file .env come indicato nelle istruzioni  e avvia il docker-compose
Le altre immagini `g3w-suite-deps` `postgis` e `nginx` verranno scaricate automaticamente.

**Comment by ghost** [comment]
![img_7](https://user-images.githubusercontent.com/88318354/130317630-5ed5e3d5-d569-433b-8641-490251ffafbe.PNG)
Grazie, riesco a scaricare i pacchetti ma non riesco a farlo partire in localhost. Questa è la schermata che ho, concluso il comando:  docker-compose up -d.
Come potrei risolvere il problema?
La ringrazio in anticipo per la risposta.

**Comment by wlorenzetti** [comment]
@Francesco2102 se tutto è partito correttamente la suite risponde sulla porta 8080, quindi +
http://localhost:8080

**Comment by ghost** [comment]
Ho scritto sul browser http://localhost:8080 ma non carica la pagina.
Non vorrei fosse un problema di configurazione del file .env.

**Comment by wlorenzetti** [comment]
Poi copiare il file `.env` qui?

**Comment by ghost** [comment]
![err_local](https://user-images.githubusercontent.com/88318354/130412508-08446a97-8264-4cfa-bee8-42984be0d507.PNG)
Questo è l'errore che ho quando eseguo http://localhost:8080.


[env.txt](https://github.com/g3w-suite/g3w-suite-docker/files/7029972/env.txt)
Per le credenziali del database ho inserito quelle di un database su digitalocean ma senza estensione postgis.

**Comment by ghost** [comment]
Provo a lasciare queste credenziali:
G3WSUITE_POSTGRES_USER_LOCAL=g3wsuite
G3WSUITE_POSTGRES_PASS=89#kL8y3D
G3WSUITE_POSTGRES_DBNAME=g3wsuite
G3WSUITE_POSTGRES_HOST=postgis
G3WSUITE_POSTGRES_PORT=5432

**Comment by wlorenzetti** [comment]
cosa dice il log?

`docker logs -f g3wsuitedocker32x_g3w-suite_1`

**Comment by ghost** [comment]
[log.txt](https://github.com/g3w-suite/g3w-suite-docker/files/7039711/log.txt)
Continua a caricare in loop queste righe.

**Comment by wlorenzetti** [comment]
E' veramente strano i worker di guinicorn falliscono e non te lo fa partire.

Fai `docker-compose down` cancella la cartella dati (mi raccomando non lasciare _/tmp/shared-volume-g3w-suite_ ma metti un path che non viene cancellato con il riavvio della macchina, fuori da tmp in sostanza ) e rifai `docker-compose up -d`

**Comment by ghost** [comment]
Non parte.

**Comment by wlorenzetti** [comment]
Ho appena provato un deploy pulito da zero ma funziona tutto correttamente, non so cosa dire.

**Comment by ghost** [comment]
Potrebbe passarmi i comandi che ha eseguito e la configurazione del file .env.
Non vorrei aver sbagliato qualcosa nella configurazione.

**Comment by wlorenzetti** [comment]
Di seguito il mio file .env:
```
WEBGIS_PUBLIC_HOSTNAME=dev.g3wsuite.it

# Shared volume mount (docker internal: shared-volume)
WEBGIS_DOCKER_SHARED_VOLUME=/home/walter/tmp/shared-volume-g3wsuite-v32x

# Suite
# Docker internal DB
G3WSUITE_POSTGRES_USER_LOCAL=g3wsuite
G3WSUITE_POSTGRES_PASS=89#kL8y3D
G3WSUITE_POSTGRES_DBNAME=g3wsuite
G3WSUITE_POSTGRES_HOST=postgis
G3WSUITE_POSTGRES_PORT=5432

G3WSUITE_QDJANGO_SERVER_URL=http://qgisserver/ows/
# set this to true to activate the frontend module
FRONTEND=False

# Caching
G3WSUITE_TILECACHE_PATH=/shared-volume/tile_cache/
TILESTACHE_CACHE_BUFFER_SIZE=256
TILESTACHE_CACHE_TOKEN=374h5g96831hsgetvmkdel

# Gunicorn workers (default to 8)
G3WSUITE_GUNICORN_NUM_WORKERS=8

# Gunicorn --max-requests value
G3WSUITE_GUNICORN_MAX_REQUESTS=200

# QGIS Server env variables
PGSERVICEFILE=/pg_service/pg_service.conf
QGIS_SERVER_PARALLEL_RENDERING=1
QGIS_SERVER_LOG_FILE=/qgis_server/error.log
MAX_CACHE_LAYERS=100
QGIS_SERVER_LOG_LEVEL=2
QGIS_SERVER_MAX_THREADS=-1
# Mounth the /qgis_server folder if you need these
QGIS_SERVER_CACHE_DIRECTORY=/qgis_server/
QGIS_SERVER_IGNORE_BAD_LAYERS=false
QGIS_SERVER_WMS_MAX_HEIGHT=-1
QGIS_SERVER_WMS_MAX_WIDTH=-1
QGIS_PLUGINPATH=/qgis_server/plugin
QGIS_SERVER_TRUST_LAYER_METADATA=1
```

ho creato la mia immagine base, inmaniera tale da avere il codice aggiornato all'ultimo commit su github:
```
docker build --build-arg G3W_SUITE_BRANCH=v.3.2.x -f Dockerfile.g3wsuite.dockerfile -t g3wsuite/g3w-suite:v3.2.x --no-cache .
```
alla fine ho lanciato il 
```
docker-compose up -d
```

**Comment by ghost** [comment]
Le credenziali del database, posso lasciare queste:
G3WSUITE_POSTGRES_USER_LOCAL=g3wsuite
G3WSUITE_POSTGRES_PASS=89#kL8y3D
G3WSUITE_POSTGRES_DBNAME=g3wsuite
G3WSUITE_POSTGRES_HOST=postgis
G3WSUITE_POSTGRES_PORT=5432

**Comment by wlorenzetti** [comment]
Si tanto se cancelli la cartella dati riparte da capo..

**Comment by ghost** [comment]
Ma oltre a questi passaggi, devo installare altre applicazioni?

**Comment by wlorenzetti** [comment]
No altro

**Comment by spaciandd** [comment]
Hi @volterra79 for **openssl**, just do following steps, it will be resolved,
```
-- Update "Dockerfile.g3wsuite.dockerfile" file,
nano Dockerfile.g3wsuite.dockerfile
# Add following line just above, "RUN apt install git -y"
RUN apt update
```
Save the file and enjoy...

**Comment by wlorenzetti** [comment]
Thanks @spaciandd I'll put it into docker file.
