### ISSUE TITLE
WMS GetCapabilities advertise on http although everything was setup as https

### ISSUE THREAD

**Issue by tudorbarascu** [g3w-suite/g3w-suite-docker#37]
Hi, first of all thanks for this very nice project and the foss4g workshop, it was great.

Now that I had time to test things in deployment I did all the steps for https and everything works out allright except the GetCapabilities response which is advertising the links with **http** instead of **https**.

Is there an extra step to follow?

Thank you,

All the best

**Comment by wlorenzetti** [comment]
Hi @tudorbarascu and sorry for replay too late :(.
Did you try with last v3.3.x branch version?

**Comment by tudorbarascu** [comment]
Hello and thanks for looking into this. Yes. I rebuild everything just now. Same result.

G3W-SUITE Version 3.3.x-20220318092230:

**Comment by wlorenzetti** [comment]
In your docker scripts folder inside `config/nginx/django.conf` and `config/nginx/django_ssl.conf` change:
```
...
proxy_set_header Host            $host:$server_port;
...
```
to
```
...
proxy_set_header Host            $host;
...
```

**Comment by tudorbarascu** [comment]
Thanks for the help. I solved it by recreating the whole suite. It seems that somehow something was cached and only by doing a full reset (with the same settings) really fixed this.
Thank you again!
