### ISSUE TITLE
Optional `ORS_API_ENDPOINT` setting ?

### ISSUE THREAD

**Issue by indeOWS** [g3w-suite/g3w-suite-docker#38]
I have had an issue to get openrouteservice application running on docker container as shown in https://github.com/GIScience/openrouteservice/issues/1129.

I wonder if I must set the variable `ORS_API_ENDPOINT` or if I can just leave it without any value in case I do not have an openrouteservice?

**Comment by wlorenzetti** [comment]
A question:
What branch did you try to run? v.3.3.x or dev?

**Comment by indeOWS** [comment]
Hi wlorenzetti. I am running v3.3.x

**Comment by wlorenzetti** [comment]
@indeOWS inside the dockerization repository you can find a `docker-compose` file where g3w-suite use openrouteservice:

https://github.com/g3w-suite/g3w-suite-docker/blob/961f54c3dd72710fa62f7d8793b2b3138c52841f/docker-compose-consumer.yml#L1-L146

Instead to use a external openrouteservice try to you this docker-compose file.

**Comment by Raruto** [comment]
As as per **v3.6.x** these are the default settings (so it would seem to be optional):

https://github.com/g3w-suite/g3w-suite-docker/blob/30d8f1a336dd2ec055390ed70f9a94aab105f66c/.env.example#L32-L40

https://github.com/g3w-suite/g3w-suite-docker/blob/30d8f1a336dd2ec055390ed70f9a94aab105f66c/config/g3w-suite/settings_docker.py#L94-L109

Feel free to open a new issue in case of more troubles.

👋 Raruto
