### ISSUE TITLE
Change default search function

### ISSUE THREAD

**Issue by GetBack2Basics** [g3w-suite/g3w-suite-docker#40]
I see that the search goes to `https://nominatim.openstreetmap.org/ui/search.html?q`

I've searched all the files for this but can't locate it. How do we change this to search within the layers available in the project or a custom search system like Solr?

Ex - https://github.com/qwc-services/qwc-fulltext-search-service

**Comment by wlorenzetti** [comment]
Sorry but at the moment is not possible to change it, because it is hard coded on g3w-client code https://github.com/g3w-suite/g3wsuite-g3w-client. It could be a new good enhancement for future versions.

**Comment by GetBack2Basics** [comment]
> Sorry but at the moment is not possible to change it, because it is hard coded on g3w-client code https://github.com/g3w-suite/g3wsuite-g3w-client. It could be a new good enhancement for future versions.

What kind of sponsored development effort would be required to add this?

**Comment by wlorenzetti** [comment]
Please @GetBack2Basics send us a official request to info@gis3w.it, so we can evaluate it and reply you with a formal quotation.
Thanks.

**Comment by GetBack2Basics** [comment]
Thanks Walter, I sent one a few days ago to this address but didn't get a
response...is there a different email to use?

**Comment by wlorenzetti** [comment]
Ok it is correct, we'll reply you as soon as possible.

**Comment by GetBack2Basics** [comment]
Hi Walter, I sent the emails via my work email ***@***.***
and haven't had a response yet. It would be great if you can get back to me
soon. 3 questions - a. use our own search db, b. include redlining and c.
use for multiple results with maps based on a template.

thanks,

**Comment by wlorenzetti** [comment]
Hi @GetBack2Basics sorry for this delay but, we are behind the release of the version v3.4.x.
For create specific search on single layers, is possible do it by creation of a 'widget search' into admin section: https://g3w-suite.readthedocs.io/en/v.3.3.x/demo.html?highlight=search#search-widget-creation

For official request I hope to reply within the week.

**Comment by GetBack2Basics** [comment]
Hi Walter,

Thanks for your email.

I haven't had a response to my emails sent to ***@***.*** sent on March
9th and March 15th from my work email ***@***.***

I would really appreciate a quote on the required enhancements.
