### ISSUE TITLE
Possible fix for FATAL: the database system is starting up

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-suite-docker#45]
I point it out here although it could be probably more a [kartoza/postgis](https://hub.docker.com/r/kartoza/postgis/) problem than a [g3wsuite/postgis](https://hub.docker.com/r/g3wsuite/postgis/) issue.

From what I understand from this topic: [dockerized-postgresql-psql-fatal-the-database-system-is-starting-up](https://stackoverflow.com/questions/42398199/dockerized-postgresql-psql-fatal-the-database-system-is-starting-up)

it seems that a parameter may be missing in the initialization (or shutdown) of the `psql` service (smart mode ??)

More info here: [postgresql-shutdown-modes](https://www.cybertec-postgresql.com/en/postgresql-shutdown-modes/)

_Have a nice day,
Raruto_

**Comment by NyakudyaA** [comment]
This does not occur on upstream kartoza postgis so I suggest this be closed and also what would it take to upgrade to the latest kartoza/postgis base image. @wlorenzetti i am not sure what else is added for the custom base image but I can do a PR to upgrade

**Comment by wlorenzetti** [comment]
@NyakudyaA thanks for you porposal, your PR is welcome :). 
I didn't work on postgis docker, It was @elpaso who worked on it, but only a `setup-database.sh` script runs as entrypoint:

https://github.com/g3w-suite/g3w-suite-docker/blob/dev/Dockerfile.postgis.dockerfile

https://github.com/g3w-suite/g3w-suite-docker/blob/dev/setup-database.sh

**Comment by wlorenzetti** [comment]
#CU-861m9uyn6[review]

**Comment by Raruto** [comment]
Fixed by: https://github.com/g3w-suite/g3w-suite-docker/pull/120
