### ISSUE TITLE
Escape special characthers within `.env.example`

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-suite-docker#52]
Currently inside the .env file there is a special character `#`, which is quite common for passwords, but as you can see this assignment is misinterpreted by the docker environment (`89#kL8y3D` becomes `89`):

https://github.com/g3w-suite/g3w-suite-docker/blob/0850eded5bd5225a88266fb1b1b5fa14dda0b352/.env.example#L10

![photo](https://user-images.githubusercontent.com/9614886/179988027-e50e87cb-7b3f-4915-9289-ab3f09bbbf34.png)

_Nothing fatal, but it can get dramatic when trying to access `psql` without understanding why 😢_

By chance do you know if there is a reference guide for escaping this weird characters? (eg. `G3WSUITE_POSTGRES_PASS="89#kL8y3D"` does not seem to be enough)

**Comment by wlorenzetti** [comment]
Do you try with single quote?
`G3WSUITE_POSTGRES_PASS='89#kL8y3D'`
