### ISSUE TITLE
Interruption of installation G3W docker on Ubuntu 18.04

### ISSUE THREAD

**Issue by nstoykov** [g3w-suite/g3w-suite-docker#6]
Hello,
I follow the instructions below:

[Install_G3W_docker_instruction.txt](https://github.com/g3w-suite/g3w-suite-docker/files/5057082/Install_G3W_docker_instruction.txt)

I come to the following result:

[Install_G3W_docker_result.txt](https://github.com/g3w-suite/g3w-suite-docker/files/5057084/Install_G3W_docker_result.txt)

would you advise me where I am wrong???

**Comment by wlorenzetti** [comment]
Hi @nstoykov ,
I just update branch dev and branch v3.0.x with new apt qgis key.

>   404  Not Found [IP: 91.189.88.142 80]
Err:15 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 git amd64 1:2.17.1-1ubuntu0.4
  404  Not Found [IP: 91.189.88.142 80]
Fetched 1677 kB in 0s (5350 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/git/git-man_2.17.1-1ubuntu0.4_all.deb  404  Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/git/git_2.17.1-1ubuntu0.4_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

For this error I suggest you to update your ubuntu:bionic docker image.. 

`docker pull ubuntu:bionic`

**Comment by nstoykov** [comment]
thank you for your cooperation
