### ISSUE TITLE
Add link and description to github repository

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-suite-docker#70]
It is advisable to add a brief description that does not force others to open the project README to easily understand what this repository is about, for example:

```
Run G3W-SUITE stack with docker-compose

https://g3w-suite.readthedocs.io/en/latest/docker.html
```

![photo](https://user-images.githubusercontent.com/9614886/190419131-d0f102e8-c36a-4448-983b-634663953f5e.png)

**Comment by wlorenzetti** [comment]
Thanks @Raruto , done it.
