### ISSUE TITLE
Error loading external layer [kml]

### ISSUE THREAD

**Issue by dmiolo** [g3w-suite/g3w-suite-docker#8]
When I try to load an external layer (kml) I get an error in loading.
From the docker logs I see no errors ...
![err_caric](https://user-images.githubusercontent.com/43961850/90731028-6213f380-e2c9-11ea-8e25-d82b5b0044fa.JPG)

**Comment by wlorenzetti** [comment]
Could you upload here your kml?

**Comment by dmiolo** [comment]
Sure:
[878_ALBERA LIGURE_BT.zip](https://github.com/g3w-suite/g3w-suite-docker/files/5102427/878_ALBERA.LIGURE_BT.zip)
Thanks!

**Comment by volterra79** [comment]
Solved

**Comment by wlorenzetti** [comment]
@dmiolo fixed on v.3.0.x branch https://github.com/g3w-suite/g3w-admin/commit/b01c97d1edcaa35e5dbb5e8563e1e6395a59607d.
Recreate g3wsuite/g3w-suite-deps:latest e rerun docker-compose.
