### ISSUE TITLE
[docker-compose-consumer.yml] - 502 Bad Gateway NGINX

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-suite-docker#88]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Once the project was configured I tried to start it no longer using the `docker-compose-dev.yml` but the `docker-compose-consumer.yml` only that although I managed to start all the containers if I refer to the login link (`http://xxx.xxx.xxx.xxx:8080`) NGINX shows me this error message:

![image](https://user-images.githubusercontent.com/24570908/205856700-8c766a2c-50f6-4980-9df0-2dfbc8fdb41c.png)

I think I have configured everything correctly both in the `.env` and `config.js` files.

I noticed that at the postgis log level I get this error message:

```
Setup master database
Initializing Postgres Database at /var/lib/postgresql/11/main
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".
**initdb: could not access directory "/var/lib/postgresql/11/main": Permission denied**

```

Do you know why this happens?

And also if I try to run the server in dev mode using the `npm run dev command` by accessing the login page `http://xxx.xxx.xxx.xxx:3000/it/` the browser

I also wanted to ask if once I solve this problem by launching the environment with this yml `docker-compose-consumer.yml` I will be able to run the server in dev mode in the same way using the `npm run dev` command the console shows me this error message:

```
[08:16:17] Error: connect ECONNREFUSED 10.4.6.193:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.4.6.193',
  port: 8000
```

I just can't get to the login page...

Thank you in advance

### Steps to reproduce

Described above

### Environment

- g3w-admin: 3.5-dev
- g3w-client: 3.7-dev
- browser: chrome
- operating system: Ubuntu Server

**Comment by bard0x** [comment]
## UPDATE:

By setting these permissions to the shared-volume folder

`sudo chmod -R 777 shared-volume/`

I managed to bypass the first postgis container error but now the console log tells me these other errors

![image](https://user-images.githubusercontent.com/24570908/205863706-6f047f70-ce29-48dc-ac29-562d876b0245.png)

when i try to go to the login page and the screenshot on the login page now gives me error 500

![image](https://user-images.githubusercontent.com/24570908/205863770-3fcfe6dc-c13f-41bd-a3b0-7b19f50640a1.png)





`

**Comment by wlorenzetti** [comment]
Hi, if you want to try G3W-SUITE in production I suggest you to use `docker-compose.yml` `docker-compose-comsumer.yml` is specific for those cases where it is necessary to activate batch procedures.

If the installation didn't get dirty.. just try `docker compose up -d` if that doesn't work I suggest you delete the directory `WEBGIS_DOCKER_SHARED_VOLUME` and start over.

**Comment by bard0x** [comment]
I'm sorry, so I wanted to know if the use of redis in the consumer is linked to a data caching on a project or other stuff... Because I was trying to start the consumer just for Redis

**Comment by wlorenzetti** [comment]
No it is not related to data caching but is used as a messaging system between containers precisely in batch operations.

**Comment by bard0x** [comment]
Thank you a lot.

One last thing, if I run the npm run dev command to start the development version of g3w, when I try to log into that port, I have no response from the browser and I get this error in the console:

```
[11:27:28] Error: connect ECONNREFUSED 10.4.6.193:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.4.6.193',
  port: 8000
}
```

How can I develop in dev mode using the `docker-compose.yml` version? And when I have made the changes, once I run the `npm run build` command how can I reverberate them on the production version?

**Comment by wlorenzetti** [comment]
`docker-compose.yml` is not for development but for deployment. you have to use the `docker-compose-dev.yml` which is for development.

However if you want to use `docker-compose.yml` I would say you should add the following declaration in the `g3w-suite` service:

```yaml
     ports:
       - "8000:8000"
```

Because the port is not externally mapped..

**Comment by bard0x** [comment]
I had already tried to do this by comparing the 2 .ymls and what happens is very strange when I try to refer to the dev server

I attach an image below:

## Admin page

![image](https://user-images.githubusercontent.com/24570908/205938844-37975e7d-1757-45c6-b0f7-59c81434b99f.png)

## Error messages

![image](https://user-images.githubusercontent.com/24570908/205938991-2fd9125c-d7c3-4e93-b290-0c2a0bf6dd94.png)


However, leaving out the fact that I could easily use `docker-compose-dev.yml` to develop, I don't understand why when I launch the build with `npm run build` I don't find the changes in the prod version.

Do I need to do anything special beyond just running the build command?

**Comment by bard0x** [comment]
@volterra79 Do you have any more info about it?
