### ISSUE TITLE
Save with only 1 click

### ISSUE THREAD

**Issue by dmiolo** [g3w-suite/g3w-suite-docker#9]
The procedure for saving the modified layers involves saving a first time in the attribute insertion form and finally saving the changes made inside the layer again to send the changes to the DB (Postgresql in my case).
![save1](https://user-images.githubusercontent.com/43961850/90747417-28df8180-e2d1-11ea-8375-cd7b18fb1181.JPG)
Is it possible to provide for the data entered to be sent directly to the first save from the attribute entry form?
![Save2](https://user-images.githubusercontent.com/43961850/90747426-2da43580-e2d1-11ea-9e6f-51411a6914d7.JPG)

**Comment by wlorenzetti** [comment]
@dmiolo for editing workflow this at the moment is not possible.
