### ISSUE TITLE
504 Gateway Time-out error

### ISSUE THREAD

**Issue by pietroblu** [g3w-suite/g3w-suite-docker#93]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

I've deployed G3W Suite on an Oracle VM with Ubuntu 22.04 on which I've previously installed Docker following the [official guide](https://docs.docker.com/engine/install/ubuntu/).

1. I've cloned the [docker repo](https://github.com/g3w-suite/g3w-suite-docker.git) on ubuntu user folder.
2. I've renamend `.env.example` file in `.env` letting it as is, intending to change the standard password later.
3. I've executed the command `docker-compose up -d`
4. I've opened the ingress port `8080` of the VM.
5. The instance issues a **502 Bad Gateway error**.

Hereafter I've attached the latest rows of the log obtained with the command `docker compose logs g3w-suite`

```log
g3w-suite_1  | [2023-02-21 20:07:08 +0000] [83] [CRITICAL] WORKER TIMEOUT (pid:198)
g3w-suite_1  | [2023-02-21 20:07:10 +0000] [83] [CRITICAL] WORKER TIMEOUT (pid:199)
g3w-suite_1  | [2023-02-21 20:07:10 +0000] [83] [CRITICAL] WORKER TIMEOUT (pid:200)
g3w-suite_1  | [2023-02-21 20:07:10 +0000] [83] [CRITICAL] WORKER TIMEOUT (pid:201)
g3w-suite_1  | [2023-02-21 20:07:10 +0000] [83] [CRITICAL] WORKER TIMEOUT (pid:202)
g3w-suite_1  | [2023-02-21 20:07:10 +0000] [83] [CRITICAL] WORKER TIMEOUT (pid:203)
g3w-suite_1  | [2023-02-21 20:07:10 +0000] [83] [CRITICAL] WORKER TIMEOUT (pid:204)
g3w-suite_1  | [2023-02-21 20:07:10 +0000] [83] [CRITICAL] WORKER TIMEOUT (pid:205)
g3w-suite_1  | [2023-02-21 20:07:14 +0000] [83] [WARNING] Worker with pid 198 was terminated due to signal 9
g3w-suite_1  | [2023-02-21 20:07:14 +0000] [83] [WARNING] Worker with pid 199 was terminated due to signal 9
g3w-suite_1  | [2023-02-21 20:07:14 +0000] [83] [WARNING] Worker with pid 200 was terminated due to signal 9
g3w-suite_1  | [2023-02-21 20:07:14 +0000] [83] [WARNING] Worker with pid 201 was terminated due to signal 9
g3w-suite_1  | [2023-02-21 20:07:14 +0000] [83] [WARNING] Worker with pid 202 was terminated due to signal 9
g3w-suite_1  | [2023-02-21 20:07:14 +0000] [83] [WARNING] Worker with pid 203 was terminated due to signal 9
g3w-suite_1  | [2023-02-21 20:07:14 +0000] [83] [WARNING] Worker with pid 204 was terminated due to signal 9
g3w-suite_1  | [2023-02-21 20:07:14 +0000] [83] [WARNING] Worker with pid 205 was terminated due to signal 9
g3w-suite_1  | [2023-02-21 20:07:14 +0000] [231] [INFO] Booting worker with pid: 231
g3w-suite_1  | [2023-02-21 20:07:14 +0000] [230] [INFO] Booting worker with pid: 230
g3w-suite_1  | [2023-02-21 20:07:15 +0000] [232] [INFO] Booting worker with pid: 232
g3w-suite_1  | [2023-02-21 20:07:15 +0000] [233] [INFO] Booting worker with pid: 233
g3w-suite_1  | [2023-02-21 20:07:15 +0000] [234] [INFO] Booting worker with pid: 234
g3w-suite_1  | [2023-02-21 20:07:15 +0000] [235] [INFO] Booting worker with pid: 235
g3w-suite_1  | [2023-02-21 20:07:15 +0000] [236] [INFO] Booting worker with pid: 236
g3w-suite_1  | [2023-02-21 20:07:15 +0000] [237] [INFO] Booting worker with pid: 237
```

What could be the problem?
Do I have to provide other useful info to solve the issue?

### Steps to reproduce

Please reach the instance at http://204.216.218.20:8080/

### Environment

- g3w-admin: __3.5__
- operating system: __Ubuntu 22.04__

### Link to your project

http://204.216.218.20:8080/

**Comment by wlorenzetti** [comment]
Hi @pietroblu the workflow seams correct. Did you try to use `dev` branch from https://github.com/g3w-suite/g3w-suite-docker.git, right?
Try with branch `v3.5.x` that is the last stable version, `dev` branch is the current development branch so it could not be work at well.

Could you past her your `.env`  file?

**Comment by pietroblu** [comment]
Hi @wlorenzetti yes, indeed I used `dev` branch from the repo (without even noticing it).
To deploy the stable branch `v3.5.x` I have to previously _uninstall_ the `dev` one?
If yes, how can I do it?
Moreover, what is the `git` command I should use to clone the stable branch `v3.5.x` instead of the dev one?

Thanks

**Comment by pietroblu** [comment]
Anyway, I've created a brand new Oracle VM with Ubuntu 22.04.
I've cloned the `v3.5.x` branch with the command `git clone --branch v3.5.x --single-branch https://github.com/g3w-suite/g3w-suite-docker.git`.
I've deployed the suite following the guide.
Now I get the 502 Bad Gateway error, here is the IP  instance [http://129.152.27.0:8080/](http://129.152.27.0:8080/)

Below find the `.env` file content.

```
# Public hostmane
WEBGIS_PUBLIC_HOSTNAME=v35.g3wsuite.it

# Shared volume mount (docker internal: shared-volume)
# I suggest not to use the /tmp/ folder, /tmp/ folder is cleaned at each reboot
WEBGIS_DOCKER_SHARED_VOLUME=./shared-volume

# Docker internal DB
G3WSUITE_POSTGRES_USER_LOCAL=g3wsuite
G3WSUITE_POSTGRES_PASS='89#kL8y3D'
G3WSUITE_POSTGRES_DBNAME=g3wsuite
G3WSUITE_POSTGRES_HOST=postgis
G3WSUITE_POSTGRES_PORT=5432

# Set this to true to activate the frontend module
FRONTEND=False

# QGIS Server env variables
# ----------------------------------------------------
PGSERVICEFILE=/pg_service/pg_service.conf
# Put your pg service into ./scripts/pg_service.conf file, the conf file will be mounted into
# docker container at runtime a the PGSERVICEFILE

QGIS_SERVER_LOG_FILE=/shared_volume/QGIS/error.log
QGIS_SERVER_LOG_LEVEL=2

# Extra QGIS env variables.
# Every QGIS environment variables available as specified on manual
# https://docs.qgis.org/3.22/en/docs/server_manual/config.html#environment-variables
# can be set, important is remember to add thy to `docker-compose.yml` o  `docker-compose-consument.yml`.

# Openrouteservice
# ----------------------------------------------------
#ORS_API_ENDPOINT='https://api.openrouteservice.org/v2'
# Optional, can be blank if the key is not required by the endpoint
#ORS_API_KEY='<your API key goes here>'
# Max number of ranges (it depends on the server configuration)
#ORS_MAX_RANGES=6
# Max number of locations(it depends on the server configuration)
#ORS_MAX_LOCATIONS=2

# Gunicorn settings
# ---------------------------------------------------------
# Timeout for Gunicorn instances. In some cases you may consider increasing this value to 240 or higher to prevent 502 errors in nginx.
G3WSUITE_GUNICORN_TIMEOUT=120

# *Important*: remember to add this env vars also to docker-compose.yml or
# docker-compose-consumer.yml
```

**Comment by wlorenzetti** [comment]
@pietroblu  as soon as possible I'll try to replicate your workflow.

**Comment by Raruto** [comment]
@pietroblu maybe a trivial question, have you tried to edit (or remove?) the following value within your `.env` file?

```
# Public hostmane
WEBGIS_PUBLIC_HOSTNAME=v35.g3wsuite.it
```

> Do I have to provide other useful info to solve the issue?

While you are waiting for an answer from a more knowledgeable person than me, I suggest you attach the remaining part of your logfile here (the one you report looks like only the end lines).

In case it's too big for a github comment, you can also simply attach a file: ref [Attaching files - GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)

---

**NB** @wlorenzetti @pietroblu I move this issue within the [g3w-suite-docker/issues](https://github.com/g3w-suite/g3w-suite-docker/issues) repository, which it seems related to

**Comment by wlorenzetti** [comment]
@pietroblu I just make a simple test on a Htzner cloud instance: Ubuntu 22.04, 2 CPU, 4GB RAM and it works.

My workflow:

1. Install Docker and Docker Compose following the official docker guide: https://docs.docker.com/engine/install/ubuntu/
2. Make clone of g3w-suite-docke repository on branch `dev`: `git clone https://github.com/g3w-suite/g3w-suite-docker.git`
3. Inside of g3w-suite-docker folder i just make a copy of .env.example file: `cp .env.example .env`, without changing nothing inside it.
4. run `docker compose up -d`

A the end my G3W-SUITE instance responde on http://<myipserver>:8080

**Comment by pietroblu** [comment]
@wlorenzetti at last it worked!

I followed your latest instructions and finally the instance is regularly accessible from the web.
I really don't know what I did wrong, but I'm afraid it's something related to docker deployment.
In fact, I noticed that now the console deployment progress interface is different from the one I used previously.

Many many thanks for your patience.
